### ISSUE TITLE
TERRA-88 ⁃ terraform-provider-astra_v2.1.0-rc9 and v2.1.6  plugins crashed

### ISSUE THREAD

**Issue by KseniiaRyuma** [datastax/terraform-provider-astra#181] opened 2022-11-04 23:46 UTC
Hi there,

Please provide the following details with your issue report.

### Terraform Version
1.3.4

### Affected Resource(s)
terraform-provider-astra_v2.1.0-rc9 plugin crashed and
terraform-provider-astra_v2.1.6 plugin crashed

[error.txt](https://github.com/datastax/terraform-provider-astra/files/9942511/error.txt)

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/TERRA-88) by [Unito](https://www.unito.io)
┆Issue Number: TERRA-88
┆Priority: Major
┆Link To Issue: https://datastax-oss.atlassian.net/browse/TERRA-88

**Comment by emerkle826** [comment] 2022-11-08 18:54
@KseniiaRyuma Can you provide a sample of your terrafrom file, or any more info about what you were attempting when you got the error?

**Comment by pgier** [comment] 2023-07-20 17:40
I'm going to close this one because we don't have enough details to reproduce and it affects older versions.  Feel free to re-open or create a new issue if the problem still exists in v.2.1.18 or higher.

**Closed by pgier** 2023-07-20 17:40 UTC
